// Code generated by "stringer -type=Month -linecomment"; DO NOT EDIT.

package calendar

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonthUnspecified-0]
	_ = x[MonthJanuary-1]
	_ = x[MonthFebruary-2]
	_ = x[MonthMarch-3]
	_ = x[MonthApril-4]
	_ = x[MonthMay-5]
	_ = x[MonthJune-6]
	_ = x[MonthJuly-7]
	_ = x[MonthAugust-8]
	_ = x[MonthSeptember-9]
	_ = x[MonthOctober-10]
	_ = x[MonthNovember-11]
	_ = x[MonthDecember-12]
}

const _Month_name = "UnspecifiedJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember"

var _Month_index = [...]uint8{0, 11, 18, 26, 31, 36, 39, 43, 47, 53, 62, 69, 77, 85}

func (i Month) String() string {
	if i < 0 || i >= Month(len(_Month_index)-1) {
		return "Month(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
