// Code generated by "stringer -type=DayOfWeek -linecomment"; DO NOT EDIT.

package date

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DayOfWeekUnspecified-0]
	_ = x[DayOfWeekMonday-1]
	_ = x[DayOfWeekTuesday-2]
	_ = x[DayOfWeekWednesday-3]
	_ = x[DayOfWeekThursday-4]
	_ = x[DayOfWeekFriday-5]
	_ = x[DayOfWeekSaturday-6]
	_ = x[DayOfWeekSunday-7]
}

const _DayOfWeek_name = "UnspecifiedMondayTuesdayWednesdayThursdayFridaySaturdaySunday"

var _DayOfWeek_index = [...]uint8{0, 11, 17, 24, 33, 41, 47, 55, 61}

func (i DayOfWeek) String() string {
	if i < 0 || i >= DayOfWeek(len(_DayOfWeek_index)-1) {
		return "DayOfWeek(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DayOfWeek_name[_DayOfWeek_index[i]:_DayOfWeek_index[i+1]]
}
